apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: data-platform-api-site-doc-reads-rmq-kube
  name: data-platform-api-site-doc-reads-rmq-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-platform-api-site-doc-reads-rmq-kube
      app: SITE_DOC
  template:
    metadata:
      labels:
        run: data-platform-api-site-doc-reads-rmq-kube
        app: SITE_DOC
    spec:
      nodeName: worker
      hostname: data-platform-api-site-doc-reads-rmq-kube
      containers:
        - name: data-platform-api-site-doc-reads-rmq-kube
          image: latonaio/data-platform-api-site-doc-reads-rmq-kube
          imagePullPolicy: Always
          env:
            - name: "RMQ_QUEUE_FROM"
              value: "data-platform-api-site-doc-reads-queue"
            - name: "RMQ_QUEUE_TO_SQL"
              value: "sql-update-kube"
            - name: "DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: data-platform-api-site-doc-reads-rmq-kube
  name: data-platform-api-site-doc-reads-rmq-kube
spec:
  selector:
    run: data-platform-api-site-doc-reads-rmq-kube
  type: ClusterIP
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
